nimbusHost: "nimbus"
nimbusPort: 6627

# whether or not to enable ganglia reporting
enableGanglia: true

# ganglia configuration (necessary if ganglia reporting is enabled)
ganglia:

   # how often to report to ganglia metrics (in seconds)
   reportInterval: 60

   # the hostname of the gmond server where storm cluster metrics will be sent
   host: "ganglia"

   # address mode
   # default is MULTICAST
   addressMode: "UNICAST"

   # an <IP>:<HOSTNAME> pair to spoof
   # this allows us to simulate storm cluster metrics coming from a specific host
   spoof: "192.168.202.11:storm"

# HTTP-specific options.
http:

  # The port on which the HTTP server listens for service requests.
  port: 8080

  # The port on which the HTTP server listens for administrative requests.
  adminPort: 8081

